version: '3'
services:
  yt-music-download-ui:
    build: .
    image: ${IMAGE}
    ports:
      - "3030:3030"
    volumes:
      - "./data/downloads:/downloads"
      - "./data/config:/config"
    environment:
      - HOST=0.0.0.0:3030
      - RUST_BACKTRACE=1
