/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AlbumType {
    #[serde(rename = "album")]
    Album,
    #[serde(rename = "single")]
    Single,
    #[serde(rename = "ep")]
    Ep,

}

impl ToString for AlbumType {
    fn to_string(&self) -> String {
        match self {
            Self::Album => String::from("album"),
            Self::Single => String::from("single"),
            Self::Ep => String::from("ep"),
        }
    }
}

impl Default for AlbumType {
    fn default() -> AlbumType {
        Self::Album
    }
}




