/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlbumGetParams {
    #[serde(rename = "browseId")]
    pub browse_id: String,
}

impl AlbumGetParams {
    pub fn new(browse_id: String) -> AlbumGetParams {
        AlbumGetParams {
            browse_id,
        }
    }
}


