/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ArtistRun {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "id", deserialize_with = "Option::deserialize")]
    pub id: Option<String>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ArtistRun {
    pub fn new(name: String, id: Option<String>, r#type: Type) -> ArtistRun {
        ArtistRun {
            name,
            id,
            r#type,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "artist")]
    Artist,
    #[serde(rename = "channel")]
    Channel,
}

impl Default for Type {
    fn default() -> Type {
        Self::Artist
    }
}

