/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Caption {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "vssId")]
    pub vss_id: String,
    #[serde(rename = "lang")]
    pub lang: String,
    #[serde(rename = "translatable")]
    pub translatable: bool,
}

impl Caption {
    pub fn new(url: String, name: String, vss_id: String, lang: String, translatable: bool) -> Caption {
        Caption {
            url,
            name,
            vss_id,
            lang,
            translatable,
        }
    }
}


