/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MenuTokens {
    #[serde(rename = "add", deserialize_with = "Option::deserialize")]
    pub add: Option<String>,
    #[serde(rename = "remove", deserialize_with = "Option::deserialize")]
    pub remove: Option<String>,
    #[serde(rename = "saved")]
    pub saved: bool,
}

impl MenuTokens {
    pub fn new(add: Option<String>, remove: Option<String>, saved: bool) -> MenuTokens {
        MenuTokens {
            add,
            remove,
            saved,
        }
    }
}


