/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MenuPlaylists {
    #[serde(rename = "shuffleId", deserialize_with = "Option::deserialize")]
    pub shuffle_id: Option<String>,
    #[serde(rename = "radioId", deserialize_with = "Option::deserialize")]
    pub radio_id: Option<String>,
}

impl MenuPlaylists {
    pub fn new(shuffle_id: Option<String>, radio_id: Option<String>) -> MenuPlaylists {
        MenuPlaylists {
            shuffle_id,
            radio_id,
        }
    }
}


