/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlaylistGetParams {
    #[serde(rename = "authPath")]
    pub auth_path: String,
    #[serde(rename = "playlistId")]
    pub playlist_id: String,
}

impl PlaylistGetParams {
    pub fn new(auth_path: String, playlist_id: String) -> PlaylistGetParams {
        PlaylistGetParams {
            auth_path,
            playlist_id,
        }
    }
}


