/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueueCurrent {
    #[serde(rename = "index", deserialize_with = "Option::deserialize")]
    pub index: Option<f64>,
    #[serde(rename = "playlistId")]
    pub playlist_id: String,
    #[serde(rename = "videoId")]
    pub video_id: String,
}

impl QueueCurrent {
    pub fn new(index: Option<f64>, playlist_id: String, video_id: String) -> QueueCurrent {
        QueueCurrent {
            index,
            playlist_id,
            video_id,
        }
    }
}


