/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueueChip {
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "playlistId")]
    pub playlist_id: String,
    #[serde(rename = "params")]
    pub params: String,
}

impl QueueChip {
    pub fn new(title: String, playlist_id: String, params: String) -> QueueChip {
        QueueChip {
            title,
            playlist_id,
            params,
        }
    }
}


