/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SongGetParams {
    #[serde(rename = "videoId")]
    pub video_id: String,
}

impl SongGetParams {
    pub fn new(video_id: String) -> SongGetParams {
        SongGetParams {
            video_id,
        }
    }
}


