/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TrendChange {
    #[serde(rename = "UP")]
    Up,
    #[serde(rename = "DOWN")]
    Down,
    #[serde(rename = "NEUTRAL")]
    Neutral,

}

impl ToString for TrendChange {
    fn to_string(&self) -> String {
        match self {
            Self::Up => String::from("UP"),
            Self::Down => String::from("DOWN"),
            Self::Neutral => String::from("NEUTRAL"),
        }
    }
}

impl Default for TrendChange {
    fn default() -> TrendChange {
        Self::Up
    }
}




