/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VideoDetails {
    #[serde(rename = "videoId")]
    pub video_id: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "lengthSeconds")]
    pub length_seconds: f64,
    #[serde(rename = "channelId")]
    pub channel_id: String,
    #[serde(rename = "isOwnerViewing")]
    pub is_owner_viewing: bool,
    #[serde(rename = "isCrawlable")]
    pub is_crawlable: bool,
    #[serde(rename = "thumbnail")]
    pub thumbnail: Box<crate::models::VideoDetailsThumbnail>,
    #[serde(rename = "allowRatings")]
    pub allow_ratings: bool,
    #[serde(rename = "viewCount")]
    pub view_count: f64,
    #[serde(rename = "author")]
    pub author: String,
    #[serde(rename = "isPrivate")]
    pub is_private: bool,
    #[serde(rename = "isUnpluggedCorpus")]
    pub is_unplugged_corpus: bool,
    #[serde(rename = "musicVideoType")]
    pub music_video_type: crate::models::VideoType,
    #[serde(rename = "isLiveContent")]
    pub is_live_content: bool,
}

impl VideoDetails {
    pub fn new(video_id: String, title: String, length_seconds: f64, channel_id: String, is_owner_viewing: bool, is_crawlable: bool, thumbnail: crate::models::VideoDetailsThumbnail, allow_ratings: bool, view_count: f64, author: String, is_private: bool, is_unplugged_corpus: bool, music_video_type: crate::models::VideoType, is_live_content: bool) -> VideoDetails {
        VideoDetails {
            video_id,
            title,
            length_seconds,
            channel_id,
            is_owner_viewing,
            is_crawlable,
            thumbnail: Box::new(thumbnail),
            allow_ratings,
            view_count,
            author,
            is_private,
            is_unplugged_corpus,
            music_video_type,
            is_live_content,
        }
    }
}


