/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VideoType {
    #[serde(rename = "MUSIC_VIDEO_TYPE_OMV")]
    Omv,
    #[serde(rename = "MUSIC_VIDEO_TYPE_UGC")]
    Ugc,
    #[serde(rename = "MUSIC_VIDEO_TYPE_ATV")]
    Atv,
    #[serde(rename = "MUSIC_VIDEO_TYPE_PRIVATELY_OWNED_TRACK")]
    PrivatelyOwnedTrack,

}

impl ToString for VideoType {
    fn to_string(&self) -> String {
        match self {
            Self::Omv => String::from("MUSIC_VIDEO_TYPE_OMV"),
            Self::Ugc => String::from("MUSIC_VIDEO_TYPE_UGC"),
            Self::Atv => String::from("MUSIC_VIDEO_TYPE_ATV"),
            Self::PrivatelyOwnedTrack => String::from("MUSIC_VIDEO_TYPE_PRIVATELY_OWNED_TRACK"),
        }
    }
}

impl Default for VideoType {
    fn default() -> VideoType {
        Self::Omv
    }
}




